### ISSUE TITLE
error on running

### ISSUE THREAD

**Issue by ayxos** [LeoAJ/react-facebook-friends#7]
After i changed the appID, i get the following error:

```
the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
```

how to configure Fb app to make it work with oauth on localhost

**Comment by LeoAJ** [comment]
It is most likely the configuration error on your Facebook API setting, you can check with Facebook developer documentation for more detail.
